### PR TITLE
Add taxonomy selector field type

### PR DESCRIPTION
**Pull request by wturnerharris**
@TimPerry - not sure if you use or maintain this, but we needed to be able to select taxonomies in a similar way. This PR just adds this but only for v5 as that's what we used. Just sharing in case this is useful for you or others.

### CODE REVIEW

**Comment by TimPerry** [comment]
Hi Wes, I am not actively maintaining this project anymore but @tyrann0us has volunteered to. Saying that this PR looks good to me :) Thank you.

**Comment by tyrann0us** [comment]
@TimPerry, I have not had time to check the PR, sorry.

**Comment by wturnerharris** [comment]
@TimPerry, no worries. Works fine on our projects. Just wanted to contribute =)

**Comment by tyrann0us** [comment]
@wturnerharris, thank you for this PR. I was wondering if you could remove all unused/commented methods and code lines? I know, they are present in the origial code, too. I will remove them there as well.

**Comment by tyrann0us** [comment]
@wturnerharris I thought about this once more. Adding the taxonomy selector would "double" this plugins's functionality. If we add it we should also update the plugin's description, `README`, `composer.json` etc. to document the new feature.
Could you extend your PR? Thanks!

**Comment by mcaskill** [comment]
I developed this as a dedicated ACF extension based on this one:
https://github.com/mcaskill/acf-field-taxonomy-selector

**Comment by tyrann0us** [comment]
If you already maintain the taxonomy selector as an independent project I'm in favor of keeping them seperated. IMHO if a user really need a Post Type _and_ Taxonomy selector he easily can install both plugins.
Closing this, but feel free to comment your thoughts.

**Comment by wturnerharris** [comment]
@tyrann0us - noted. Would update those if you still want it. @mcaskill - good to know the v5 code could be used. We have forked and merged the "features" together since we always need both. Thanks!

**Comment by tyrann0us** [comment]
Sorry guys, I overlooked you are two different people ... 😄 
@wturnerharris, I hope it's ok for you that I closed this PR.

**Comment by wturnerharris** [comment]
@tyrann0us no worries. it's all good. we'll maintain our fork! Thanks for the great work on the post type selector field. Without it, we were scrambling to find the taxonomy one, didn't see the one by @mcaskill

**Comment by mcaskill** [comment]
The two fields could be merged into one plugin. I'm also open to add contributors to the taxonomy selector since I haven't had a chance to play with either in over a year.

**Pull request closed without merging**
